---
- hosts:  all
  become: yes
  become_method: sudo
  gather_facts: false
  ignore_errors: true
  ignore_unreachable: true
  vars:
    ignore_errors: true
    ignore_unreachable: true
    amazonlinuxcis_level1: true
    amazonlinuxcis_level2: true
  tasks:
  - name: "Check if the host is reachable"
    setup:
    register: setup_status
    ignore_errors: yes
    tags:
      - always

  - name: "Group reachable hosts"
    group_by: key=reachable
    ignore_errors: yes
    when:
      - setup_status is defined and not setup_status.unreachable is defined
    tags:
      - always

- hosts: reachable
  serial:
    - 1
    - "50%"
    - "75%"
    - "100%"
  become: yes
  become_method: sudo
  gather_facts: true
  ignore_errors: false
  ignore_unreachable: true
  vars:
    ignore_errors: false
    ignore_unreachable: true
    amazonlinuxcis_level1: true
    amazonlinuxcis_level2: true
  roles:
    - role: CIS_awslinux1_Benchmark
  post_tasks:
    - meta: clear_host_errors
      when: ignore_unreachable
